CREATE DATABASE IF NOT EXISTS ranga_aqui;
USE ranga_aqui;

CREATE TABLE Produtos (
	ID VARCHAR(8) NOT NULL,
	Tipo VARCHAR(20) NOT NULL,
	Nome VARCHAR(30) NOT NULL,
	Preco FLOAT NOT NULL,
	Descricao VARCHAR(255),
	Status ENUM('Disponível', 'Não disponível'),
	PRIMARY KEY(ID)
);

CREATE TABLE Clientes (
	Nome VARCHAR(30) NOT NULL,
	Sobrenome VARCHAR(30) NOT NULL,
	Rua VARCHAR(45) NOT NULL,
	Numero SMALLINT UNSIGNED,
	Complemento VARCHAR(15),
	Bairro VARCHAR(15) NOT NULL,
	Cidade VARCHAR(20) NOT NULL,
	UF ENUM('MG', 'SP', 'RJ', 'ES' , 'BA', 'PR', 'SC', 'RS', 'GO', 'AC') NOT NULL,
	CEP VARCHAR(9) NOT NULL,
	CPF VARCHAR(14) NOT NULL,
	Telefone VARCHAR(15),
	PRIMARY KEY (CPF)
);

CREATE TABLE Vendas (
	CPF_Cliente VARCHAR(14) NOT NULL,
	ID_produto VARCHAR(8) NOT NULL,
	Data_pedido TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	Descricao VARCHAR(255),
	Codigo INT(3) UNSIGNED NOT NULL AUTO_INCREMENT,
	PRIMARY KEY(Codigo)
);

ALTER TABLE Vendas
ADD CONSTRAINT CPF_Cliente
FOREIGN KEY (CPF_Cliente)
REFERENCES Clientes(CPF)
ON UPDATE CASCADE;

ALTER TABLE Vendas
ADD CONSTRAINT ID_produto
FOREIGN KEY (ID_produto)
REFERENCES Produtos(ID)
ON UPDATE CASCADE;
